### ISSUE TITLE
Error with 'to' property in MessageRequest Interface - Wrong Type or Invalid

### ISSUE THREAD

**Issue by samR-auxout** [Bandwidth-Samples/messaging-send-receive-sms-js#12]
The MessageRequest interface defines the 'to' property as a Set<string>. However, when using this interface to construct a request body for creating a message, an error is encountered.

`
const body: MessageRequest = {
    from: BW_NUMBER,
    applicationId: BW_MESSAGING_APPLICATION_ID,
    to: new Set([USER_NUMBER]), // "+12345678902, +12345678903"
    text: "test message",
  };

  const messagesApi = await new MessagesApi(config);
  const response = await messagesApi.createMessage(BW_ACCOUNT_ID, body);
`
Error Message: 

data: {
  type: 'request-validation',
  description: 'Your request could not be accepted. ',
  fieldErrors: [
    {
      fieldName: 'to',
      description: 'The value at line 1, column 84 is the wrong type or is invalid. Please check the API documentation for more details.'
    }
  ]
}

Steps to Reproduce:

- Define the to property in the MessageRequest interface as a Set<string>.

- Create a request body using the defined interface.

- Attempt to send the request to create a message with the specified 'to' property values.

- Observe the encountered error.

Expected Behavior:
The 'to' property in the MessageRequest interface should be compatible with creating a message, and no validation errors should occur.

Actual Behavior:
Validation error occurs with the description "The value at line 1, column 84 is the wrong type or is invalid."

**Comment by ckoegel** [comment]
Hey, @samR-auxout 
This was a bug in v1 of the SDK that has been fixed as of v2.0.0
